import { StyleSheet } from "react-native";

import { borderRadius, colors, spacing, typography } from "../theme/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: 0,
  },
  screen: {
    flex: 1,
    paddingTop: spacing.sm,
    position: "relative",
  },
  prepRoot: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  prepImageBg: {
    flex: 1,
    width: "100%",
  },
  prepInner: {
    flex: 1,
  },
  prepContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
  },
  prepMainBlock: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  prepHeadingBlock: {
    alignItems: "center",
    width: "100%",
  },
  prepTeamPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm + 2,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.surface,
  },
  prepTeamPillAzul: {
    backgroundColor: colors.primaryLight,
  },
  prepTeamPillRojo: {
    backgroundColor: colors.secondary,
  },
  prepTeamPillText: {
    fontSize: typography.sizes.lg,
    fontFamily: typography.families.heading,
    color: colors.textLight,
    letterSpacing: 1.2,
  },
  prepTurnRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  prepTurnText: {
    fontSize: typography.sizes.xxxl,
    fontFamily: typography.families.heading,
    color: colors.sparkle,
    letterSpacing: 2,
  },
  prepPickupTitle: {
    fontSize: typography.sizes.xxxl,
    fontFamily: typography.families.heading,
    color: colors.textLight,
    textAlign: "center",
    textTransform: "uppercase",
    marginBottom: spacing.lg,
  },
  prepPlayerCardOuter: {
    width: "100%",
    marginBottom: spacing.lg,
  },
  prepPlayerCard: {
    width: "100%",
    minHeight: 200,
    borderRadius: borderRadius.xxl,
    borderWidth: 2,
    borderColor: colors.gamePrepPlayerCardBorder,
    backgroundColor: colors.gamePrepPlayerCard,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    overflow: "hidden",
  },
  prepPlayerCardSparkleTL: {
    position: "absolute",
    top: spacing.md,
    left: spacing.md,
  },
  prepPlayerCardSparkleBR: {
    position: "absolute",
    bottom: spacing.md,
    right: spacing.md,
  },
  prepPlayerNameLine: {
    fontSize: 56,
    lineHeight: 58,
    fontFamily: typography.families.heading,
    color: colors.textLight,
    textAlign: "center",
    textTransform: "uppercase",
  },
  prepPlayerNameLineSecondary: {
    marginTop: spacing.xs,
  },
  prepStatsRow: {
    width: "100%",
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  prepStatWrap: {
    flex: 1,
    alignItems: "center",
    paddingTop: spacing.lg,
  },
  prepStatIconCircle: {
    position: "absolute",
    top: 0,
    alignSelf: "center",
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    borderWidth: 3,
    borderColor: colors.textLight,
  },
  prepStatIconBlue: {
    backgroundColor: colors.primary,
  },
  prepStatIconPurple: {
    backgroundColor: colors.accuracyAccent,
  },
  prepStatCard: {
    width: "100%",
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    borderRadius: borderRadius.xl,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  prepStatCardBlue: {
    backgroundColor: colors.primaryLight,
  },
  prepStatCardPurple: {
    backgroundColor: colors.accuracyAccent,
  },
  prepStatLabel: {
    fontSize: typography.sizes.sm,
    color: colors.textLight,
    fontFamily: typography.families.bodyBold,
    letterSpacing: 2,
  },
  prepStatValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  prepStatValue: {
    fontSize: typography.sizes.display,
    lineHeight: typography.sizes.display,
    color: colors.textLight,
    fontFamily: typography.families.heading,
  },
  prepStartShell: {
    width: "100%",
    alignItems: "center",
  },
  prepStartRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    width: "100%",
  },
  prepStartSparkleSide: {
    paddingBottom: 4,
  },
  prepStartPressable: {
    flex: 1,
    maxWidth: 440,
  },
  prepStartAnimated: {
    minHeight: 64,
    borderRadius: borderRadius.full,
    backgroundColor: colors.gamePrepStart,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 4,
    borderBottomColor: colors.tertiary,
  },
  prepStartLabel: {
    color: colors.textLight,
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xl,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  playingBgRoot: {
    flex: 1,
    width: "100%",
  },
  playingBgContent: {
    flex: 1,
  },
  playingStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  playingTeamScoreColumn: {
    width: 96,
    alignItems: "center",
    gap: spacing.xs,
  },
  playingTeamLabelRed: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.secondary,
    letterSpacing: 1.2,
  },
  playingTeamLabelBlue: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.primary,
    letterSpacing: 1.2,
  },
  playingScoreBoxShadowRed: {
    borderRadius: borderRadius.lg,
    borderBottomWidth: 6,
    borderBottomColor: colors.secondary,
    overflow: "hidden",
    minWidth: 88,
  },
  playingScoreBoxShadowBlue: {
    borderRadius: borderRadius.lg,
    borderBottomWidth: 6,
    borderBottomColor: colors.primary,
    overflow: "hidden",
    minWidth: 88,
  },
  playingScoreBoxInner: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
  },
  playingScoreBoxRed: {
    backgroundColor: colors.teamRojoTint,
  },
  playingScoreBoxBlue: {
    backgroundColor: colors.teamAzulTint,
  },
  playingScoreValueText: {
    fontSize: typography.sizes.xxxl,
    lineHeight: typography.sizes.xxxl + 2,
    fontFamily: typography.families.bodyBold,
  },
  playingScoreValueRed: {
    color: colors.secondary,
  },
  playingScoreValueBlue: {
    color: colors.primary,
  },
  playingTimerRingWrap: {
    width: 140,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  playingTimerSvg: {
    position: "absolute",
  },
  playingTimerCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  playingTimerCenterText: {
    fontSize: 56,
    lineHeight: 56,
    fontFamily: typography.families.heading,
    color: colors.titleNavy,
  },
  playingWordCard: {
    marginHorizontal: spacing.lg,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xxl,
    minHeight: 260,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxxl,
    marginBottom: spacing.lg,
    borderBottomWidth: 8,
    borderBottomColor: colors.outlineVariant,
    position: "relative",
  },
  playingWordBadgeTL: {
    position: "absolute",
    top: spacing.lg,
    left: spacing.lg,
    width: 52,
    height: 52,
    borderRadius: borderRadius.full,
    backgroundColor: colors.gameTurnCardBadgeBg,
    alignItems: "center",
    justifyContent: "center",
  },
  playingWordBadgeBR: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    width: 52,
    height: 52,
    borderRadius: borderRadius.full,
    backgroundColor: colors.gameTurnCardBadgeBg,
    alignItems: "center",
    justifyContent: "center",
  },
  playingWordBadgeText: {
    color: colors.gameTurnCardBadgeText,
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xxl,
  },
  playingWordText: {
    fontSize: 52,
    lineHeight: 56,
    fontFamily: typography.families.heading,
    color: colors.titleNavy,
    textAlign: "center",
    textTransform: "uppercase",
    paddingHorizontal: spacing.sm,
  },
  playingWordProgressTrack: {
    width: "88%",
    maxWidth: 320,
    height: 12,
    borderRadius: borderRadius.full,
    backgroundColor: colors.teamAzulTint,
    marginTop: spacing.lg,
    overflow: "hidden",
    alignSelf: "center",
    flexDirection: "row",
  },
  playingWordProgressFill: {
    height: "100%",
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
  },
  playingActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  playingPhasePillSlot: {
    flex: 1,
    marginHorizontal: spacing.sm,
    alignItems: "stretch",
  },
  playingRoundActionHit: {
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  playingRoundActionInner: {
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  playingRoundActionPressed: {
    opacity: 0.88,
  },
  playingIncorrectDecorWrap: {
    position: "absolute",
    width: 52,
    height: 52,
    top: spacing.xs,
    left: spacing.xs,
    zIndex: 2,
  },
  playingIncorrectRay: {
    position: "absolute",
    width: 18,
    height: 5,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.secondary,
  },
  playingIncorrectRayA: {
    top: 2,
    left: 4,
    transform: [{ rotate: "-38deg" }],
  },
  playingIncorrectRayB: {
    top: 14,
    left: 0,
    transform: [{ rotate: "-8deg" }],
  },
  playingIncorrectRayC: {
    top: 26,
    left: 2,
    transform: [{ rotate: "12deg" }],
  },
  playingIncorrectCircle: {
    width: 112,
    height: 112,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    borderBottomWidth: 6,
    borderBottomColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  playingCorrectDecorWrap: {
    position: "absolute",
    width: 52,
    height: 52,
    top: spacing.xs,
    right: spacing.xs,
    zIndex: 2,
  },
  playingCorrectRay: {
    position: "absolute",
    width: 18,
    height: 5,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.gamePrepStart,
  },
  playingCorrectRayA: {
    top: 2,
    right: 4,
    transform: [{ rotate: "38deg" }],
  },
  playingCorrectRayB: {
    top: 14,
    right: 0,
    transform: [{ rotate: "8deg" }],
  },
  playingCorrectRayC: {
    top: 26,
    right: 2,
    transform: [{ rotate: "-12deg" }],
  },
  playingCorrectCircle: {
    width: 112,
    height: 112,
    borderRadius: borderRadius.full,
    backgroundColor: colors.gamePrepStart,
    borderBottomWidth: 6,
    borderBottomColor: colors.tertiary,
    alignItems: "center",
    justifyContent: "center",
  },
  playingPhasePillShadow: {
    borderRadius: borderRadius.full,
    borderBottomWidth: 5,
    borderBottomColor: colors.gameTurnPhasePillBorder,
    overflow: "hidden",
    minHeight: 72,
  },
  playingPhasePillInner: {
    minHeight: 72,
    borderRadius: borderRadius.full,
    backgroundColor: colors.gameTurnPhasePillBg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  playingPhasePillText: {
    fontFamily: typography.families.bodyBold,
    color: colors.gameTurnPhasePillBorder,
    fontSize: typography.sizes.lg,
    letterSpacing: 1.2,
    textAlign: "center",
    textTransform: "uppercase",
  },
  playingFooter: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  playingFooterLabel: {
    fontFamily: typography.families.bodyBold,
    color: colors.navMuted,
    fontSize: typography.sizes.sm,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  playingFooterPlayer: {
    fontFamily: typography.families.heading,
    color: colors.appHeaderTitle,
    fontSize: 44,
    lineHeight: 48,
    textAlign: "center",
  },
  playingFooterAccent: {
    width: 72,
    height: 6,
    marginTop: spacing.xs,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.appHeaderBadge,
  },
  playingAvatarPill: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    backgroundColor: colors.appHeaderBadge,
    alignItems: "center",
    justifyContent: "center",
  },
  playingAvatarInitial: {
    fontFamily: typography.families.heading,
    color: colors.textLight,
    fontSize: typography.sizes.lg,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
  },
  errorText: {
    fontSize: typography.sizes.lg,
    color: colors.error,
    textAlign: "center",
    marginBottom: spacing.lg,
  },
  errorButton: {
    backgroundColor: colors.primary,
  },
});
