import { StyleSheet } from "react-native";

import { borderRadius, colors, spacing, typography } from "../theme/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: 0,
  },
  screen: {
    flex: 1,
    paddingTop: spacing.xs,
    position: "relative",
  },
  playingWhiteBg: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  prepRoot: {
    flex: 1,
  },
  prepImageBg: {
    flex: 1,
    width: "100%",
  },
  prepInner: {
    flex: 1,
  },
  prepContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
  },
  prepMainBlock: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  prepHeadingBlock: {
    alignItems: "center",
    width: "100%",
  },
  prepTeamPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm + 2,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.background,
  },
  prepTeamPillAzul: {
    backgroundColor: colors.accent,
  },
  prepTeamPillRojo: {
    backgroundColor: colors.secondary,
  },
  prepTeamPillText: {
    fontSize: typography.sizes.lg,
    fontFamily: typography.families.heading,
    color: '#ffffff',
    letterSpacing: 1.2,
  },
  prepTurnRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  prepTurnText: {
    fontSize: typography.sizes.xxxl,
    fontFamily: typography.families.heading,
    color: colors.accent,
    letterSpacing: 2,
  },
  prepPickupTitle: {
    fontSize: typography.sizes.xxxl,
    fontFamily: typography.families.heading,
    color: '#ffffff',
    textAlign: "center",
    textTransform: "uppercase",
    marginBottom: spacing.lg,
  },
  prepPlayerCardOuter: {
    width: "100%",
    marginBottom: spacing.lg,
  },
  prepPlayerCard: {
    width: "100%",
    minHeight: 200,
    borderRadius: borderRadius.xxl,
    borderWidth: 2,
    borderColor: colors.accent,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    overflow: "hidden",
  },
  prepPlayerCardSparkleTL: {
    position: "absolute",
    top: spacing.md,
    left: spacing.md,
  },
  prepPlayerCardSparkleBR: {
    position: "absolute",
    bottom: spacing.md,
    right: spacing.md,
  },
  prepPlayerNameLine: {
    fontSize: 56,
    lineHeight: 58,
    fontFamily: typography.families.heading,
    color: '#ffffff',
    textAlign: "center",
    textTransform: "uppercase",
  },
  prepPlayerNameLineSecondary: {
    marginTop: spacing.xs,
  },
  prepStatsRow: {
    width: "100%",
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  prepStatWrap: {
    flex: 1,
    alignItems: "center",
    paddingTop: spacing.lg,
  },
  prepStatIconCircle: {
    position: "absolute",
    top: 0,
    alignSelf: "center",
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    borderWidth: 3,
    borderColor: '#ffffff',
  },
  prepStatIconBlue: {
    backgroundColor: colors.primary,
  },
  prepStatIconPurple: {
    backgroundColor: colors.accent,
  },
  prepStatCard: {
    width: "100%",
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    borderRadius: borderRadius.xl,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  prepStatCardBlue: {
    backgroundColor: colors.accent,
  },
  prepStatCardPurple: {
    backgroundColor: colors.accent,
  },
  prepStatLabel: {
    fontSize: typography.sizes.sm,
    color: '#ffffff',
    fontFamily: typography.families.bodyBold,
    letterSpacing: 2,
  },
  prepStatValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  prepStatValue: {
    fontSize: typography.sizes.display,
    lineHeight: typography.sizes.display,
    color: '#ffffff',
    fontFamily: typography.families.heading,
  },
  prepStartShell: {
    width: "100%",
    alignItems: "center",
  },
  prepStartButton: {
    width: "100%",
    maxWidth: 440,
    borderRadius: borderRadius.full,
  },
  prepStartButtonContent: {
    minHeight: 52,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  prepStartButtonLabel: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.lg,
    letterSpacing: 0.15,
  },
  playingBgRoot: {
    flex: 1,
    width: "100%",
  },
  playingBgContent: {
    flex: 1,
  },
  playingStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  playingTeamScoreColumn: {
    width: 96,
    alignItems: "center",
    gap: spacing.xs,
  },
  playingTeamLabelRed: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.secondary,
    letterSpacing: 1.2,
  },
  playingTeamLabelBlue: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.primary,
    letterSpacing: 1.2,
  },
  playingScoreBoxShadowRed: {
    borderRadius: borderRadius.lg,
    borderBottomWidth: 6,
    borderBottomColor: colors.secondary,
    overflow: "hidden",
    minWidth: 88,
  },
  playingScoreBoxShadowBlue: {
    borderRadius: borderRadius.lg,
    borderBottomWidth: 6,
    borderBottomColor: colors.primary,
    overflow: "hidden",
    minWidth: 88,
  },
  playingScoreBoxInner: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
  },
  playingScoreBoxRed: {
    backgroundColor: colors.secondary,
  },
  playingScoreBoxBlue: {
    backgroundColor: colors.secondary,
  },
  playingScoreValueText: {
    fontSize: typography.sizes.xxxl,
    lineHeight: typography.sizes.xxxl + 2,
    fontFamily: typography.families.bodyBold,
  },
  playingScoreValueRed: {
    color: colors.secondary,
  },
  playingScoreValueBlue: {
    color: colors.primary,
  },
  playingStatsCompactWrap: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  playingStatsCompactRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  playingStatsCompactRowBase: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  playingStatsCompactNameLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  playingStatsNameClusterCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    maxWidth: "58%",
  },
  playingStatsCompactTime: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.lg,
    color: colors.text,
    fontVariant: ["tabular-nums"],
    minWidth: 44,
  },
  playingStatsPlayerBadge: {
    alignSelf: "center",
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "62%",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
  },
  playingStatsPlayerBadgeText: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    color: '#ffffff',
    textAlign: "center",
    textTransform: "uppercase",
  },
  playingStatsCompactCounts: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexShrink: 0,
  },
  playingStatsCompactCount: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    fontVariant: ["tabular-nums"],
  },
  playingStatsCompactCountSep: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.sm,
    color: colors.text,
    opacity: 0.45,
  },
  playingStatsCompactTrack: {
    height: 3,
    marginTop: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    overflow: "hidden",
  },
  playingStatsCompactFill: {
    height: "100%",
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
  },
  playingWordCard: {
    flex: 1,
    marginHorizontal: spacing.lg,
    backgroundColor: colors.background,
    borderRadius: borderRadius.xxl,
    minHeight: 200,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    marginBottom: spacing.md,
  },
  playingWordBadgeTL: {
    position: "absolute",
    top: spacing.lg,
    left: spacing.lg,
    width: 52,
    height: 52,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  playingWordBadgeBR: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    width: 52,
    height: 52,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  playingWordBadgeText: {
    color: colors.text,
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xxl,
  },
  playingWordText: {
    fontSize: 48,
    lineHeight: 52,
    fontFamily: typography.families.heading,
    color: colors.text,
    textAlign: "center",
    textTransform: "uppercase",
    paddingHorizontal: spacing.sm,
  },
  playingWordLabel: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    color: colors.primary,
    letterSpacing: 1.2,
    marginBottom: spacing.md,
    textTransform: "uppercase",
    opacity: 0.85,
  },
  playingWordProgressTrack: {
    width: "88%",
    maxWidth: 320,
    height: 12,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    marginTop: spacing.lg,
    overflow: "hidden",
    alignSelf: "center",
    flexDirection: "row",
  },
  playingWordProgressFill: {
    height: "100%",
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
  },
  playingActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  playingPhasePillSlot: {
    flex: 1,
    marginHorizontal: spacing.sm,
    alignItems: "stretch",
  },
  playingRoundActionHit: {
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  playingRoundActionInner: {
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  playingRoundActionPressed: {
    opacity: 0.88,
  },
  playingIncorrectDecorWrap: {
    position: "absolute",
    width: 52,
    height: 52,
    top: spacing.xs,
    left: spacing.xs,
    zIndex: 2,
  },
  playingIncorrectRay: {
    position: "absolute",
    width: 18,
    height: 5,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.secondary,
  },
  playingIncorrectRayA: {
    top: 2,
    left: 4,
    transform: [{ rotate: "-38deg" }],
  },
  playingIncorrectRayB: {
    top: 14,
    left: 0,
    transform: [{ rotate: "-8deg" }],
  },
  playingIncorrectRayC: {
    top: 26,
    left: 2,
    transform: [{ rotate: "12deg" }],
  },
  playingIncorrectCircle: {
    width: 112,
    height: 112,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    borderBottomWidth: 6,
    borderBottomColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  playingCorrectDecorWrap: {
    position: "absolute",
    width: 52,
    height: 52,
    top: spacing.xs,
    right: spacing.xs,
    zIndex: 2,
  },
  playingCorrectRay: {
    position: "absolute",
    width: 18,
    height: 5,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.primary,
  },
  playingCorrectRayA: {
    top: 2,
    right: 4,
    transform: [{ rotate: "38deg" }],
  },
  playingCorrectRayB: {
    top: 14,
    right: 0,
    transform: [{ rotate: "8deg" }],
  },
  playingCorrectRayC: {
    top: 26,
    right: 2,
    transform: [{ rotate: "-12deg" }],
  },
  playingCorrectCircle: {
    width: 112,
    height: 112,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    borderBottomWidth: 6,
    borderBottomColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  playingPhasePillShadow: {
    borderRadius: borderRadius.full,
    borderBottomWidth: 5,
    borderBottomColor: colors.accent,
    overflow: "hidden",
    minHeight: 72,
  },
  playingPhasePillInner: {
    minHeight: 72,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  playingPhasePillText: {
    fontFamily: typography.families.bodyBold,
    color: colors.accent,
    fontSize: typography.sizes.lg,
    letterSpacing: 1.2,
    textAlign: "center",
    textTransform: "uppercase",
  },
  playingActionColumn: {
    width: "100%",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    marginBottom: spacing.xl,
    gap: spacing.lg,
  },
  playingQuestionText: {
    textAlign: "center",
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.lg,
    color: colors.text,
  },
  playingButtonsRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  playingCorrectButton: {
    flex: 1,
    backgroundColor: '#34A853',
    borderRadius: borderRadius.xl,
    minHeight: 152,
    paddingVertical: spacing.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  playingIncorrectButton: {
    flex: 1,
    backgroundColor: '#EA4335',
    borderRadius: borderRadius.xl,
    minHeight: 152,
    paddingVertical: spacing.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  playingButtonContent: {
    alignItems: "center",
    gap: spacing.sm,
  },
  playingButtonIconCircle: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xs,
  },
  playingButtonMainText: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: '#ffffff',
  },
  playingButtonSubText: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    color: '#ffffff',
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  playingFooter: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  playingFooterLabel: {
    fontFamily: typography.families.bodyBold,
    color: colors.text,
    fontSize: typography.sizes.sm,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  playingFooterPlayer: {
    fontFamily: typography.families.heading,
    color: colors.primary,
    fontSize: 44,
    lineHeight: 48,
    textAlign: "center",
  },
  playingFooterAccent: {
    width: 72,
    height: 6,
    marginTop: spacing.xs,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.primary,
  },
  playingAvatarPill: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  playingAvatarInitial: {
    fontFamily: typography.families.heading,
    color: '#ffffff',
    fontSize: typography.sizes.lg,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
  },
  errorText: {
    fontSize: typography.sizes.lg,
    color: colors.accent,
    textAlign: "center",
    marginBottom: spacing.lg,
  },
  errorButton: {
    backgroundColor: colors.primary,
  },
});
