import { StyleSheet } from "react-native";

import {
  borderRadius,
  colors,
  spacing,
  typography,
} from "../theme/theme";

export const styles = StyleSheet.create({
  screenContent: {
    flex: 1,
    paddingHorizontal: 0,
  },
  root: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollInner: {
    paddingHorizontal: spacing.lg,
  },
  sectionDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.secondary,
    marginVertical: spacing.xl,
  },
  loadingBlock: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  loadingLabel: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.md,
    color: colors.text,
  },
  sectionHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  sectionIconCircle: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionHeadingTitle: {
    flex: 1,
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.md,
    color: colors.text,
    letterSpacing: 0.2,
  },
  generalGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  generalCell: {
    flex: 1,
    alignItems: "center",
    gap: spacing.sm,
  },
  generalGlyphCircle: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  generalGlyphTintBlue: {
    backgroundColor: colors.secondary,
  },
  generalGlyphTintRed: {
    backgroundColor: colors.secondary,
  },
  generalGlyphTintPurple: {
    backgroundColor: colors.secondary,
  },
  generalStatValueGames: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: colors.primary,
    lineHeight: typography.sizes.xxxl + spacing.xs,
  },
  generalStatValueWords: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: colors.accent,
    lineHeight: typography.sizes.xxxl + spacing.xs,
  },
  generalStatValueAccuracy: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: colors.accent,
    lineHeight: typography.sizes.xxxl + spacing.xs,
  },
  generalStatLabel: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.text,
    textAlign: "center",
  },
  teamsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.xs,
  },
  teamPanel: {
    flex: 1,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.xl,
    alignItems: "center",
    gap: spacing.sm,
  },
  teamPanelBlue: {
    backgroundColor: colors.secondary,
    marginRight: -spacing.sm,
  },
  teamPanelRed: {
    backgroundColor: colors.secondary,
    marginLeft: -spacing.sm,
  },
  teamCountBlue: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: colors.primary,
    lineHeight: typography.sizes.xxxl + spacing.xs,
  },
  teamCountRed: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.xxxl,
    color: colors.accent,
    lineHeight: typography.sizes.xxxl + spacing.xs,
  },
  teamName: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    color: colors.text,
    textAlign: "center",
  },
  teamPillBlue: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.accent,
    marginTop: spacing.xs,
  },
  teamPillRed: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.accent,
    marginTop: spacing.xs,
  },
  teamPillTextBlue: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.primary,
  },
  teamPillTextRed: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.xs,
    color: colors.accent,
  },
  vsCluster: {
    width: spacing.xxxl + spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    position: "relative",
  },
  vsTickLeft: {
    position: "absolute",
    width: spacing.lg + spacing.xs,
    height: 4,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.primary,
    left: -spacing.lg + spacing.xs,
    top: "50%",
    marginTop: -2,
    transform: [{ rotate: "-22deg" }],
  },
  vsTickRight: {
    position: "absolute",
    width: spacing.lg + spacing.xs,
    height: 4,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.accent,
    right: -spacing.lg + spacing.xs,
    top: "50%",
    marginTop: -2,
    transform: [{ rotate: "22deg" }],
  },
  vsCircle: {
    width: spacing.xxxl + spacing.md,
    height: spacing.xxxl + spacing.md,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.secondary,
  },
  vsText: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.md,
    color: colors.text,
  },
  tiesBanner: {
    marginTop: spacing.md,
    alignItems: "center",
  },
  tiesText: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.xs,
    color: colors.text,
  },
  emptyHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginTop: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  emptyHistoryGlyph: {
    width: spacing.xxl,
    height: spacing.xxl,
    borderRadius: borderRadius.full,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyHistoryTexts: {
    flex: 1,
    gap: spacing.xs,
  },
  emptyHistoryTitle: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.md,
    color: colors.text,
  },
  emptyHistorySubtitle: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.sm,
    color: colors.text,
    lineHeight: typography.sizes.md + spacing.xs,
  },
  historyDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.secondary,
    marginVertical: spacing.sm,
  },
  historyRowOuter: {},
  historyRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.xs,
    gap: spacing.sm,
  },
  historyRowTitle: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.md,
    color: colors.text,
  },
  historyRowMeta: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.xs,
    color: colors.text,
  },
  historyRowScores: {
    fontFamily: typography.families.bodyBold,
    fontSize: typography.sizes.sm,
    color: colors.text,
  },
  historyRowDeck: {
    fontFamily: typography.families.body,
    fontSize: typography.sizes.sm,
    color: colors.text,
  },
  chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  historyChipGames: {
    backgroundColor: colors.secondary,
    height: 28,
  },
  historyChipGamesText: {
    fontSize: typography.sizes.xs,
    color: colors.primary,
    marginVertical: 0,
  },
  historyChipPrecision: {
    backgroundColor: colors.secondary,
    height: 28,
  },
  historyChipPrecisionText: {
    fontSize: typography.sizes.xs,
    color: colors.accent,
    marginVertical: 0,
  },
  footerDock: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    backgroundColor: "transparent",
    gap: spacing.sm,
  },
  footerCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    minHeight: 56,
    borderRadius: borderRadius.xxl,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
  },
  footerCtaLabel: {
    fontFamily: typography.families.heading,
    fontSize: typography.sizes.sm,
    letterSpacing: 0.9,
    color: colors.background,
    textAlign: "center",
  },
});
