import { MD3LightTheme } from 'react-native-paper';

export const colors = {
  primary: '#005ab2',
  secondary: '#b31e03',
  tertiary: '#3f6600',
  background: '#ffffff',
  surface: '#ffffff',
  surfaceVariant: '#f2e6d8',
  text: '#005ab2',
  textLight: '#ffffff',
  textSecondary: '#6f5f50',
  onSurface: '#2a1e12',
  error: '#b31e03',
  accent: '#b31e03',
  outline: '#e6d4be',
  outlineVariant: '#f2e0c9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#fff8f0',
  surfaceContainerHigh: '#f2e6d8',
  backgroundLight: '#ffffff',
  primaryLight: '#2196f3',
  sparkle: '#FFCC00',
  teamAzulTint: '#E8F1FC',
  teamRojoTint: '#FCE8E8',
  teamAzulBadge: '#C5DBF5',
  teamRojoBadge: '#F2D6D6',
  headerPatternDot: '#2b6fbe',
  navActivePill: '#C8E3FF',
  navMuted: '#8A95A8',
  titleNavy: '#0D1B3D',
  accuracyAccent: '#6D28D9',
  accuracyTint: '#F3E8FF',
  statisticsSectionDivider: '#B8D7F8',
  gamePrepStart: '#8BC34A',
  gamePrepPlayerCard: '#0a4F9C',
  gamePrepPlayerCardBorder: '#5BA3F5',
  gamePrepTopBar: '#FFFFFF',
  appHeaderTitle: '#0D63F3',
  appHeaderBadge: '#0D63F3',
  gameTurnTimerTrack: '#FFF8F9',
  gameTurnCardBadgeBg: '#EDE4D3',
  gameTurnCardBadgeText: '#5C4033',
  gameTurnPhasePillBg: '#DCF5DE',
  gameTurnPhasePillBorder: '#2E7D32',
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  xxxl: 64,
};

export const borderRadius = {
  xs: 4,
  sm: 6,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  full: 9999,
};

export const typography = {
  families: {
    display: 'PlusJakartaSans_800ExtraBold',
    heading: 'PlusJakartaSans_800ExtraBold',
    body: 'BeVietnamPro_400Regular',
    bodyBold: 'BeVietnamPro_700Bold',
  },
  sizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    display: 48,
  },
  weights: {
    light: '300',
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
};

export const animation = {
  fast: 150,
  normal: 300,
  slow: 500,
  slower: 700,
};

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    secondary: colors.secondary,
    tertiary: colors.tertiary,
    background: colors.background,
    surface: colors.surface,
    surfaceVariant: colors.surfaceVariant,
    text: colors.text,
    onSurface: colors.onSurface,
    error: colors.error,
    outline: colors.outline,
    outlineVariant: colors.outlineVariant,
  },
  roundness: borderRadius.md,
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: {
      ...MD3LightTheme.fonts.displayLarge,
      fontFamily: typography.families.display,
      fontWeight: '800' as const,
    },
    headlineLarge: {
      ...MD3LightTheme.fonts.headlineLarge,
      fontFamily: typography.families.heading,
      fontWeight: '800' as const,
    },
    titleLarge: {
      ...MD3LightTheme.fonts.titleLarge,
      fontFamily: typography.families.bodyBold,
      fontWeight: '700' as const,
    },
    bodyLarge: {
      ...MD3LightTheme.fonts.bodyLarge,
      fontFamily: typography.families.body,
      fontWeight: '400' as const,
    },
  },
  elevation: {
    level0: 0,
    level1: 1,
    level2: 3,
    level3: 6,
    level4: 8,
    level5: 12,
  },
};
